### ISSUE TITLE
Site Content

### ISSUE THREAD

**Issue by colinrjv** [MTM6330-F17/mtm6330-final-project-team7#7]
https://docs.google.com/document/d/1dC05GsqblST2bUySsomD3agtU6_UjXZXIaOYprqQPSY/edit?usp=sharing

- a program overview
- a class schedule for all sections in the current semester
- a detailed page describing each course, the topics covered, the professor, and the grading
- a detailed page describing each professor, their contact information and the courses taught

Each team should include detail pages for at least 3 courses and 3 professors. Try to include more informative details than what is currently included on the public website. You might consult the detailed week by week topic outline for each course.

**Comment by gabriellepc11** [comment]
Made changes for the program overview! Still waiting on the class schedule
